name: 'Configuration Manager'
type: module
description: 'Allows importing and exporting configuration changes.'
package: Core
# version: VERSION
configure: config.sync

# Information added by Drupal.org packaging script on 2025-08-07
version: '11.2.3'
project: 'drupal'
datestamp: 1754563438
